version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "5 0 * * *"
    groups:
      github-actions:
        patterns: ["*"]
